import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EAG_HOME, CLAUDE_CONFIG_DIR } from './paths.js';
import { exists, readJson, writeFileAtomic, backup, deepEqual } from './util.js';

// The shell wrapper only covers terminal launches. An agent started from a desktop app or
// an IDE extension reads no rc, so the agent's own session hook is the only way in — and it
// runs in an environment the user never configured.
export const LAUNCHER = path.join(EAG_HOME, 'bin', 'eag-sync');
const ENTRY = fileURLToPath(new URL('../bin/eag.js', import.meta.url));

// A GUI-launched agent on macOS gets PATH=/usr/bin:/bin:/usr/sbin:/sbin, where node does
// not exist. So the hook cannot call `eag` (a node shebang script) and cannot rely on PATH:
// the launcher is POSIX sh with the interpreter and the entry point baked in as absolute
// paths, and it falls back to a search if that node ever moves (an nvm upgrade, say).
export function renderLauncher({ node = process.execPath, entry = ENTRY } = {}) {
  return `#!/bin/sh
# Generated by eag (easy-agnostic). Rewritten by \`eag hook install\`.
#
# Run from an agent's SessionStart hook, which starts with a minimal environment: a
# GUI-launched agent has no shell rc and, on macOS, no node on PATH. Everything below is
# either an absolute path or a search, and every failure is silent — a sync problem must
# never stop an agent from opening.
NODE='${node}'
EAG='${entry}'
[ -x "$NODE" ] || NODE=$(command -v node 2>/dev/null)
for c in /usr/local/bin/node /opt/homebrew/bin/node "$HOME/.local/bin/node"; do
  [ -x "$NODE" ] && break
  [ -x "$c" ] && NODE="$c"
done
[ -x "$NODE" ] || exit 0
[ -f "$EAG" ] || exit 0
"$NODE" "$EAG" apply --quiet >/dev/null 2>&1
exit 0
`;
}

export function writeLauncher({ dryRun = false } = {}) {
  const text = renderLauncher();
  const current = exists(LAUNCHER) ? fs.readFileSync(LAUNCHER, 'utf8') : null;
  if (current === text) return { file: LAUNCHER, changed: false };
  if (!dryRun) { fs.mkdirSync(path.dirname(LAUNCHER), { recursive: true }); writeFileAtomic(LAUNCHER, text, 0o755); }
  return { file: LAUNCHER, changed: true, created: current === null };
}

// ---- Claude Code -----------------------------------------------------------------------
// ~/.claude/settings.json is the user's own file and holds unrelated settings, so eag reads
// it, adds exactly one SessionStart entry, and writes it back. No matcher: fire on every
// start. The command is the launcher, never `eag` itself, for the PATH reason above.
export const CLAUDE_SETTINGS = path.join(CLAUDE_CONFIG_DIR, 'settings.json');
const claudeCommand = () => `/bin/sh ${LAUNCHER}`;
const isOurs = (h) => typeof h?.command === 'string' && h.command.includes(LAUNCHER);

// `timeout` is not optional: a SessionStart command hook with no timeout blocks session
// startup for as long as it runs (measured: a 75s hook held startup for 75s, uncapped). An
// apply takes ~150ms, so 20s is generous and still bounded. `async` is a bonus on builds
// that honour it; the timeout is the guarantee.
//
// The launcher already redirects its own output, which matters more than it looks: for
// SessionStart, "exit code 0 - stdout shown to Claude" — anything printed would be injected
// into the session as context.
export function claudeEntry() { return { type: 'command', command: claudeCommand(), timeout: 20, async: true }; }

export function claudeState() {
  const s = readJson(CLAUDE_SETTINGS, null);
  const groups = Array.isArray(s?.hooks?.SessionStart) ? s.hooks.SessionStart : [];
  const found = groups.flatMap((g) => (Array.isArray(g?.hooks) ? g.hooks : [])).filter(isOurs);
  return {
    file: CLAUDE_SETTINGS,
    exists: s !== null,
    installed: found.length > 0,
    // The whole entry, not just the command: a change to `timeout` matters as much as a
    // change to the path, and comparing only the command left an old entry in place.
    current: found.length === 1 && deepEqual(found[0], claudeEntry()),
    settings: s,
  };
}

const isPlainObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);

export function installClaude({ dryRun = false, backupDir } = {}) {
  const st = claudeState();
  if (st.current) return { file: CLAUDE_SETTINGS, changed: false };
  // A settings file that parses but is not an object is broken, not empty. Writing over it
  // would destroy whatever the user meant to have there.
  if (st.exists && !isPlainObject(st.settings)) {
    throw new Error(`${CLAUDE_SETTINGS} is not a JSON object; fix it by hand, then run eag hook install`);
  }
  const s = st.exists ? structuredClone(st.settings) : {};
  s.hooks = s.hooks && typeof s.hooks === 'object' ? s.hooks : {};
  const groups = (Array.isArray(s.hooks.SessionStart) ? s.hooks.SessionStart : [])
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !isOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  s.hooks.SessionStart = [...groups, { hooks: [claudeEntry()] }];
  if (!dryRun) {
    if (st.exists && backupDir) backup(CLAUDE_SETTINGS, backupDir, 'claude-settings');
    fs.mkdirSync(path.dirname(CLAUDE_SETTINGS), { recursive: true });
    writeFileAtomic(CLAUDE_SETTINGS, `${JSON.stringify(s, null, 2)}\n`);
  }
  return { file: CLAUDE_SETTINGS, changed: true, created: !st.exists };
}

export function uninstallClaude({ dryRun = false, backupDir } = {}) {
  const st = claudeState();
  if (!st.exists || !st.installed) return { file: CLAUDE_SETTINGS, changed: false };
  const s = structuredClone(st.settings);
  // Take out our entry and any group it leaves empty, and the SessionStart/hooks keys if
  // they end up empty — but never anything else in the file.
  s.hooks.SessionStart = s.hooks.SessionStart
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !isOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  if (!s.hooks.SessionStart.length) delete s.hooks.SessionStart;
  if (!Object.keys(s.hooks).length) delete s.hooks;
  if (!dryRun) {
    if (backupDir) backup(CLAUDE_SETTINGS, backupDir, 'claude-settings');
    writeFileAtomic(CLAUDE_SETTINGS, `${JSON.stringify(s, null, 2)}\n`);
  }
  return { file: CLAUDE_SETTINGS, changed: true };
}
