import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { EAG_HOME, CLAUDE_CONFIG_DIR, CODEX_HOME } from './paths.js';
import { exists, readJson, writeFileAtomic, backup, deepEqual, shellQuote } from './util.js';

// The shell wrapper only covers terminal launches. An agent started from a desktop app or
// an IDE extension reads no rc, so the agent's own session hook is the only way in — and it
// runs in an environment the user never configured.
export const LAUNCHER = path.join(EAG_HOME, 'bin', 'eag-sync');
const ENTRY = fileURLToPath(new URL('../bin/eag.js', import.meta.url));

// A GUI-launched agent on macOS gets PATH=/usr/bin:/bin:/usr/sbin:/sbin, where node does
// not exist. So the hook cannot call `eag` (a node shebang script) and cannot rely on PATH:
// the launcher is POSIX sh with the interpreter and the entry point baked in as absolute
// paths, and it falls back to a search if that node ever moves (an nvm upgrade, say).
// `binDir` is the npm global bin dir, baked in at install time. The launcher prefers the
// `eag` found there (or on PATH) over the entry point it was generated from, so an upgrade
// installed with `npm i -g` takes effect on the next launch with no rewrite — and so a
// launcher generated from an npx cache keeps working after that cache is gone.
export function renderLauncher({ node = process.execPath, entry = ENTRY, binDir = null } = {}) {
  return `#!/bin/sh
# Generated by eag (easy-agnostic). Rewritten by \`eag hook install\`.
#
# Run from an agent's SessionStart hook, which starts with a minimal environment: a
# GUI-launched agent has no shell rc and, on macOS, no node on PATH. Everything below is
# either an absolute path or a search, and every failure is silent — a sync problem must
# never stop an agent from opening.
NODE=${shellQuote(node)}
EAG=${shellQuote(entry)}
BIN=${shellQuote(binDir ?? '')}
[ -x "$NODE" ] || NODE=$(command -v node 2>/dev/null)
for c in /usr/local/bin/node /opt/homebrew/bin/node "$HOME/.local/bin/node"; do
  [ -x "$NODE" ] && break
  [ -x "$c" ] && NODE="$c"
done
[ -x "$NODE" ] || exit 0
# The installed \`eag\` first (it is what \`npm i -g\` upgrades), the generating package last.
# Always through "$NODE": the installed one is a node script too, and PATH has no node here.
for c in "$BIN/eag" "$HOME/.local/bin/eag" /usr/local/bin/eag /opt/homebrew/bin/eag "$EAG"; do
  [ -n "$c" ] && [ -f "$c" ] && { "$NODE" "$c" apply --quiet >/dev/null 2>&1; exit 0; }
done
exit 0
`;
}

export function writeLauncher({ dryRun = false, binDir = null } = {}) {
  const text = renderLauncher({ binDir });
  const current = exists(LAUNCHER) ? fs.readFileSync(LAUNCHER, 'utf8') : null;
  if (current === text) return { file: LAUNCHER, changed: false };
  if (!dryRun) { fs.mkdirSync(path.dirname(LAUNCHER), { recursive: true }); writeFileAtomic(LAUNCHER, text, 0o755); }
  return { file: LAUNCHER, changed: true, created: current === null };
}

// ---- Claude Code -----------------------------------------------------------------------
// ~/.claude/settings.json is the user's own file and holds unrelated settings, so eag reads
// it, adds exactly one SessionStart entry, and writes it back. No matcher: fire on every
// start. The command is the launcher, never `eag` itself, for the PATH reason above.
export const CLAUDE_SETTINGS = path.join(CLAUDE_CONFIG_DIR, 'settings.json');
const claudeCommand = () => `/bin/sh ${shellQuote(LAUNCHER)}`;
const isOurs = (h) => typeof h?.command === 'string' && (h.command.includes(LAUNCHER) || h.command.includes(shellQuote(LAUNCHER)));

// `timeout` is not optional: a SessionStart command hook with no timeout blocks session
// startup for as long as it runs (measured: a 75s hook held startup for 75s, uncapped). An
// apply takes ~150ms, so 20s is generous and still bounded. `async` is a bonus on builds
// that honour it; the timeout is the guarantee.
//
// The launcher already redirects its own output, which matters more than it looks: for
// SessionStart, "exit code 0 - stdout shown to Claude" — anything printed would be injected
// into the session as context.
export function claudeEntry() { return { type: 'command', command: claudeCommand(), timeout: 20, async: true }; }

export function claudeState() {
  const s = readJson(CLAUDE_SETTINGS, null);
  const groups = Array.isArray(s?.hooks?.SessionStart) ? s.hooks.SessionStart : [];
  const found = groups.flatMap((g) => (Array.isArray(g?.hooks) ? g.hooks : [])).filter(isOurs);
  return {
    file: CLAUDE_SETTINGS,
    exists: s !== null,
    installed: found.length > 0,
    // The whole entry, not just the command: a change to `timeout` matters as much as a
    // change to the path, and comparing only the command left an old entry in place.
    current: found.length === 1 && deepEqual(found[0], claudeEntry()),
    settings: s,
  };
}

const isPlainObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);

export function installClaude({ dryRun = false, backupDir } = {}) {
  const st = claudeState();
  if (st.current) return { file: CLAUDE_SETTINGS, changed: false };
  // A settings file that parses but is not an object is broken, not empty. Writing over it
  // would destroy whatever the user meant to have there.
  if (st.exists && !isPlainObject(st.settings)) {
    throw new Error(`${CLAUDE_SETTINGS} is not a JSON object; fix it by hand, then run eag hook install`);
  }
  const s = st.exists ? structuredClone(st.settings) : {};
  s.hooks = s.hooks && typeof s.hooks === 'object' ? s.hooks : {};
  const groups = (Array.isArray(s.hooks.SessionStart) ? s.hooks.SessionStart : [])
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !isOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  s.hooks.SessionStart = [...groups, { hooks: [claudeEntry()] }];
  if (!dryRun) {
    if (st.exists && backupDir) backup(CLAUDE_SETTINGS, backupDir, 'claude-settings');
    fs.mkdirSync(path.dirname(CLAUDE_SETTINGS), { recursive: true });
    writeFileAtomic(CLAUDE_SETTINGS, `${JSON.stringify(s, null, 2)}\n`);
  }
  return { file: CLAUDE_SETTINGS, changed: true, created: !st.exists };
}

export function uninstallClaude({ dryRun = false, backupDir } = {}) {
  const st = claudeState();
  if (!st.exists || !st.installed) return { file: CLAUDE_SETTINGS, changed: false };
  const s = structuredClone(st.settings);
  // Take out our entry and any group it leaves empty, and the SessionStart/hooks keys if
  // they end up empty — but never anything else in the file.
  s.hooks.SessionStart = s.hooks.SessionStart
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !isOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  if (!s.hooks.SessionStart.length) delete s.hooks.SessionStart;
  if (!Object.keys(s.hooks).length) delete s.hooks;
  if (!dryRun) {
    if (backupDir) backup(CLAUDE_SETTINGS, backupDir, 'claude-settings');
    writeFileAtomic(CLAUDE_SETTINGS, `${JSON.stringify(s, null, 2)}\n`);
  }
  return { file: CLAUDE_SETTINGS, changed: true };
}

// ---- Codex ------------------------------------------------------------------------------
// $CODEX_HOME/hooks.json is discovered implicitly — no pointer in config.toml. (The `hooks`
// key the binary documents as "Hook config path" is a plugin.json field, not a config one.)
// The shape is the same as Claude's, which is not a coincidence: Codex mirrored it.
export const CODEX_HOOKS = path.join(CODEX_HOME, 'hooks.json');
const codexIsOurs = isOurs;

// No statusMessage: it renders a spinner label, and a sync nobody asked to watch should not
// put anything on screen. timeout for the same reason it is set for Claude.
export function codexEntry() { return { type: 'command', command: claudeCommand(), timeout: 20 }; }

export function codexState() {
  const f = readJson(CODEX_HOOKS, null);
  const groups = Array.isArray(f?.hooks?.SessionStart) ? f.hooks.SessionStart : [];
  const found = groups.flatMap((g) => (Array.isArray(g?.hooks) ? g.hooks : [])).filter(codexIsOurs);
  return {
    file: CODEX_HOOKS,
    exists: f !== null,
    installed: found.length > 0,
    current: found.length === 1 && deepEqual(found[0], codexEntry()),
    hooks: f,
  };
}

export function installCodex({ dryRun = false, backupDir } = {}) {
  const st = codexState();
  if (st.current) return { file: CODEX_HOOKS, changed: false };
  if (st.exists && !isPlainObject(st.hooks)) {
    throw new Error(`${CODEX_HOOKS} is not a JSON object; fix it by hand, then run eag hook install`);
  }
  const f = st.exists ? structuredClone(st.hooks) : {};
  f.hooks = isPlainObject(f.hooks) ? f.hooks : {};
  const groups = (Array.isArray(f.hooks.SessionStart) ? f.hooks.SessionStart : [])
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !codexIsOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  f.hooks.SessionStart = [...groups, { hooks: [codexEntry()] }];
  if (!dryRun) {
    if (st.exists && backupDir) backup(CODEX_HOOKS, backupDir, 'codex-hooks');
    fs.mkdirSync(path.dirname(CODEX_HOOKS), { recursive: true });
    writeFileAtomic(CODEX_HOOKS, `${JSON.stringify(f, null, 2)}\n`);
  }
  return { file: CODEX_HOOKS, changed: true, created: !st.exists };
}

export function uninstallCodex({ dryRun = false, backupDir } = {}) {
  const st = codexState();
  if (!st.exists || !st.installed) return { file: CODEX_HOOKS, changed: false };
  const f = structuredClone(st.hooks);
  f.hooks.SessionStart = f.hooks.SessionStart
    .map((g) => (Array.isArray(g?.hooks) ? { ...g, hooks: g.hooks.filter((h) => !codexIsOurs(h)) } : g))
    .filter((g) => !Array.isArray(g?.hooks) || g.hooks.length > 0);
  if (!f.hooks.SessionStart.length) delete f.hooks.SessionStart;
  const empty = !Object.keys(f.hooks).length;
  if (empty) delete f.hooks;
  if (!dryRun) {
    if (backupDir) backup(CODEX_HOOKS, backupDir, 'codex-hooks');
    if (empty && !Object.keys(f).length) fs.rmSync(CODEX_HOOKS, { force: true });
    else writeFileAtomic(CODEX_HOOKS, `${JSON.stringify(f, null, 2)}\n`);
  }
  return { file: CODEX_HOOKS, changed: true };
}

// Codex will not run a hook it has not been told to trust, and it says NOTHING when it
// skips one: a user who never opens /hooks would believe sync-on-launch works. eag cannot
// grant that trust itself — it lives in config.toml outside the managed block, and eag does
// not edit there — so the least it must do is ask Codex and report the answer.
//
// Best effort by construction: no Codex, a slow daemon or a changed RPC returns null, and
// the caller says "unknown" rather than failing anything.
// Async because stdin has to stay open until the answer arrives: the server reads requests
// as a stream, and closing the pipe after writing (what execFileSync does) makes it exit
// before it has replied.
export function codexTrust({ timeoutMs = 8000 } = {}) {
  if (!exists(CODEX_HOOKS)) return Promise.resolve(null);
  return new Promise((resolve) => {
    let p;
    try {
      p = spawn('codex', ['app-server'], { stdio: ['pipe', 'pipe', 'ignore'] });
    } catch { resolve(null); return; }
    let done = false;
    let timer;
    const finish = (v) => { if (done) return; done = true; clearTimeout(timer); try { p.kill('SIGKILL'); } catch { /* already gone */ } resolve(v); };
    timer = setTimeout(() => finish(null), timeoutMs);
    timer.unref?.();
    p.on('error', () => finish(null));
    p.on('close', () => finish(null));
    p.stdin.on('error', () => finish(null));
    let buf = '';
    p.stdout.on('data', (d) => {
      if (done) return;
      buf += d;
      if (buf.length > 4 * 1024 * 1024) { finish(null); return; }
      const lines = buf.split('\n');
      buf = lines.pop();
      for (const line of lines) {
        let j;
        try { j = JSON.parse(line); } catch { continue; }
        if (j?.id !== 2) continue;
        clearTimeout(timer);
        const all = (j.result?.data || []).flatMap((d2) => d2.hooks || []);
        const ours = all.filter((h) => h.sourcePath === CODEX_HOOKS && isOurs(h));
        finish(ours.length ? { key: ours[0].key, hash: ours[0].currentHash, status: ours[0].trustStatus, enabled: ours[0].enabled } : null);
        return;
      }
    });
    for (const r of [
      { jsonrpc: '2.0', id: 1, method: 'initialize', params: { clientInfo: { name: 'eag', title: 'eag', version: '0' } } },
      { jsonrpc: '2.0', method: 'initialized', params: {} },
      { jsonrpc: '2.0', id: 2, method: 'hooks/list', params: {} },
    ]) { try { p.stdin.write(`${JSON.stringify(r)}\n`); } catch { finish(null); return; } }
  });
}
