import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { EAG_HOME } from './paths.js';
import { exists, writeFileAtomic, backup } from './util.js';

// eag writes into an agent's own config, so an agent that is already running reads whatever
// was on disk when it started. The cheapest place to close that gap is the shell: every
// terminal-launched agent passes through it, so a wrapper can sync just before the process
// starts — earlier than a SessionStart hook, which fires after the agent read its config.
export const INIT_FILE = path.join(EAG_HOME, 'shell-init.sh');
export const BEGIN = '# >>> easy-agnostic >>>';
export const END = '# <<< easy-agnostic <<<';

// Only agents eag has to WRITE for. Pi is deliberately absent: it reads the source itself,
// so opening it can never find a stale config, and wrapping it would buy nothing.
export const AGENT_BINS = { claude: 'claude', codex: 'codex' };

function onPath(bin) {
  for (const dir of (process.env.PATH || '').split(path.delimiter)) {
    if (!dir) continue;
    try { fs.accessSync(path.join(dir, bin), fs.constants.X_OK); return true; } catch { /* keep looking */ }
  }
  return false;
}

// Wrap only what is installed: a function named after a missing binary would make
// `command -v codex` succeed for a Codex that is not there. Anything installed later is
// picked up the next time this file is regenerated, which every `eag apply` does.
export function wrappableBins() {
  return [...new Set(Object.values(AGENT_BINS))].filter(onPath).sort();
}

// The npm global bin dir, baked in at install time: the rc may not have it on PATH yet,
// and an npx-only install has no `eag` on PATH at all. Resolved by the caller.
export function render(bins = wrappableBins(), { binDir = null } = {}) {
  return [
    BEGIN,
    '# Generated by eag (easy-agnostic). Do not edit by hand: it is rewritten by',
    '# `eag hook install` and refreshed by every `eag apply`.',
    '#',
    '# Two jobs, both only while eag is installed:',
    '#   1. export the ${NAME} values the agents expand from their own environment. The',
    '#      values are read from the secret store on each shell start and are never',
    '#      written into this file.',
    '#   2. sync each agent just before it starts, so it cannot read a stale config.',
    '#      `eag apply --quiet` prints nothing when there is nothing to do, and refuses',
    '#      to write when it finds a conflict.',
    ...(binDir ? [`[ -x "${binDir}/eag" ] && case ":$PATH:" in *":${binDir}:"*) ;; *) PATH="${binDir}:$PATH";; esac`] : []),
    'if command -v eag >/dev/null 2>&1; then',
    '  eval "$(command eag env)"',
    ...(bins.length
      ? ['', '  __eag_sync() { command eag apply --quiet || true; }',
         ...bins.map((b) => `  ${b}() { __eag_sync; command ${b} "$@"; }`)]
      : ['', '  # no agent binary on PATH yet; install one and run `eag hook install`']),
    'fi',
    END,
    '',
  ].join('\n');
}

export function rcPath() {
  if (process.env.EAG_SHELL_RC) return process.env.EAG_SHELL_RC;
  const shell = process.env.SHELL || '';
  if (shell.endsWith('fish')) return path.join(os.homedir(), '.config', 'fish', 'config.fish');
  if (shell.endsWith('bash')) return path.join(os.homedir(), '.bashrc');
  return path.join(os.homedir(), '.zshrc');
}
export function isFish(rc = rcPath()) { return rc.endsWith('.fish'); }

export function rcSnippet(file = INIT_FILE) {
  // Guarded on the file existing, so deleting it (or uninstalling eag) can never leave a
  // shell that refuses to start.
  return `${BEGIN}\n[ -f "${file}" ] && . "${file}"\n${END}\n`;
}

const LEGACY_ENV = /^\s*eval\s+"\$\(\s*eag env\s*\)"\s*$/;
// Any comment a person (or an older README) wrote directly above that line describes it, so
// removing the line without the comment leaves litter in someone's rc.
const LEGACY_COMMENT = /^\s*#.*\b(eag|easy[- ]agnostic)\b/i;

// The block, plus the bare `eval "$(eag env)"` line the README used to recommend: the
// generated file does that now, and running it twice would just cost another keychain read.
function strip(text) {
  const block = new RegExp(`\\n?${BEGIN}[\\s\\S]*?${END}\\n?`, 'g');
  const lines = text.replace(block, '\n').split('\n');
  const drop = new Set();
  lines.forEach((l, i) => {
    if (!LEGACY_ENV.test(l)) return;
    drop.add(i);
    for (let j = i - 1; j >= 0 && (LEGACY_COMMENT.test(lines[j]) || lines[j].trim() === ''); j--) {
      if (LEGACY_COMMENT.test(lines[j])) drop.add(j);
      else if (!drop.size || !drop.has(j + 1)) break; // a blank line only goes with a comment above it
    }
  });
  return lines.filter((_, i) => !drop.has(i)).join('\n');
}

export function rcState(rc = rcPath()) {
  const text = exists(rc) ? fs.readFileSync(rc, 'utf8') : '';
  return {
    rc,
    exists: exists(rc),
    linked: text.includes(BEGIN) && text.includes(INIT_FILE),
    legacyEnvLine: text.split('\n').some((l) => /^\s*eval\s+"\$\(\s*eag env\s*\)"\s*$/.test(l)),
    text,
  };
}

// Write the generated file only when its content would change, so `eag apply` can call this
// on every run without touching mtimes or piling up backups.
export function writeInit(bins = wrappableBins(), { dryRun = false, binDir = null } = {}) {
  const text = render(bins, { binDir });
  const current = exists(INIT_FILE) ? fs.readFileSync(INIT_FILE, 'utf8') : null;
  if (current === text) return { file: INIT_FILE, changed: false };
  if (!dryRun) writeFileAtomic(INIT_FILE, text);
  return { file: INIT_FILE, changed: true, created: current === null };
}

// Which binaries the file on disk already wraps. Needed because a refresh can run from an
// environment that cannot see them all.
export function binsInFile(file = INIT_FILE) {
  if (!exists(file)) return [];
  const out = [];
  for (const m of fs.readFileSync(file, 'utf8').matchAll(/^ {2}([A-Za-z0-9_-]+)\(\) \{ __eag_sync;/gm)) out.push(m[1]);
  return out;
}

// Refresh an init file that already exists. Never creates one: someone who has not run
// `eag hook install` has not asked eag to touch their shell.
//
// Only ever ADDS. A refresh can be triggered by the SessionStart launcher, which runs with
// the minimal PATH a GUI launch has — no claude, no codex — and rebuilding the list from
// that would quietly delete every wrapper and stop terminal launches syncing. Dropping a
// wrapper is therefore only ever done by an explicit `eag hook install`.
export function binDirInFile(file = INIT_FILE) {
  if (!exists(file)) return null;
  const m = fs.readFileSync(file, 'utf8').match(/^\[ -x "([^"]+)\/eag" \]/m);
  return m ? m[1] : null;
}

export function refreshInit() {
  if (!exists(INIT_FILE)) return null;
  const bins = [...new Set([...binsInFile(), ...wrappableBins()])].sort();
  const r = writeInit(bins, { binDir: binDirInFile() });
  return r.changed ? r : null;
}

export function installRc({ dryRun = false, backupDir } = {}) {
  const st = rcState();
  const stripped = strip(st.text);
  const body = stripped.replace(/\n+$/, '');
  const text = `${body ? `${body}\n\n` : ''}${rcSnippet()}`;
  if (text === st.text) return { rc: st.rc, changed: false, replacedLegacy: false };
  if (!dryRun) {
    if (st.exists && backupDir) backup(st.rc, backupDir, `rc-${path.basename(st.rc)}`);
    writeFileAtomic(st.rc, text);
  }
  return { rc: st.rc, changed: true, replacedLegacy: st.legacyEnvLine, created: !st.exists };
}

export function uninstallRc({ dryRun = false, backupDir } = {}) {
  const st = rcState();
  if (!st.exists) return { rc: st.rc, changed: false };
  const text = `${strip(st.text).replace(/\n+$/, '')}\n`;
  if (text === st.text) return { rc: st.rc, changed: false };
  if (!dryRun) {
    if (backupDir) backup(st.rc, backupDir, `rc-${path.basename(st.rc)}`);
    writeFileAtomic(st.rc, text);
  }
  return { rc: st.rc, changed: true };
}
